const Data = (() => {
  let teams = [];
  let venues = [];
  let matches = [];
  let squads = {};
  let lastUpdated = null;
  let lastOpts = { squads: false };
  let pollTimer = null;
  let loaded = false;
  let squadsLoaded = false;
  const teamByCode = new Map();
  const venueById = new Map();
  let refreshListeners = [];

  // Prefer the live serverless endpoint (/api/results) when it's deployed and
  // a key is configured; otherwise transparently fall back to the static file.
  // This makes the same build work on Vercel (live) and anywhere static.
  async function loadSchedule(bust) {
    try {
      const res = await fetch('/api/results' + bust);
      if (res.ok) {
        const data = await res.json();
        if (data && Array.isArray(data.matches) && data.matches.length) return data;
      }
      // 204 (no key) / 404 (no function locally) / 5xx -> fall through.
    } catch (e) { /* network/offline -> fall through */ }
    return fetch('data/schedule.json' + bust).then(r => r.json());
  }

  async function load(opts = {}, force = false) {
    const include = { squads: false, ...opts };
    lastOpts = include;
    // Idempotent: skip the round-trip if we already hold what's needed (the SPA
    // router calls load() on every view init). Polling passes force=true.
    if (!force && loaded && (!include.squads || squadsLoaded)) return;
    // Cache-bust so an open tab picks up files regenerated by the cron.
    const bust = `?t=${Date.now()}`;
    const fetches = [
      fetch('data/teams.json' + bust).then(r => r.json()),
      fetch('data/venues.json' + bust).then(r => r.json()),
      loadSchedule(bust)
    ];
    if (include.squads) fetches.push(fetch('data/squads.json' + bust).then(r => r.json()));
    const [t, v, s, sq] = await Promise.all(fetches);
    teams = t.teams;
    venues = v.venues;
    matches = s.matches;
    lastUpdated = s.lastUpdated || null;
    if (sq) squads = sq;

    teamByCode.clear();
    venueById.clear();
    teams.forEach(team => teamByCode.set(team.code, team));
    venues.forEach(venue => venueById.set(venue.id, venue));

    loaded = true;
    if (include.squads) squadsLoaded = true;

    // Data changed -> drop cached strengths and recompute live ratings.
    if (typeof Predict !== 'undefined' && Predict.clearCache) Predict.clearCache();
    if (typeof Ratings !== 'undefined' && Ratings.recompute) Ratings.recompute();
  }

  // Re-fetch the latest data and notify listeners (used by polling and manual
  // refresh). Reuses the include options from the initial load().
  async function reload() {
    await load(lastOpts, true);
    refreshListeners.forEach(fn => { try { fn(); } catch (e) { console.error(e); } });
  }

  // Poll for fresh data every `ms`. Returns a stop function.
  function startPolling(ms = 60000) {
    stopPolling();
    pollTimer = setInterval(() => { reload().catch(console.error); }, ms);
    return stopPolling;
  }
  function stopPolling() {
    if (pollTimer) { clearInterval(pollTimer); pollTimer = null; }
  }

  const onRefresh = fn => { refreshListeners.push(fn); };
  // The SPA router clears a view's refresh hooks before swapping to the next.
  const clearRefreshListeners = () => { refreshListeners = []; };

  const getTeams = () => teams;
  const getMatches = () => matches;
  const getTeam = code => teamByCode.get(code);
  const getVenue = id => venueById.get(id);
  const getSquad = code => squads[code] || [];
  const getLastUpdated = () => lastUpdated;

  // Delegate to Predict module when available (full strength model);
  // otherwise fall back to a FIFA-rank-only estimate.
  function predict(match) {
    if (!match.home || !match.away) return null;
    const home = getTeam(match.home);
    const away = getTeam(match.away);
    if (!home || !away) return null;
    if (typeof Predict !== 'undefined' && Predict.predictMatch) {
      return Predict.predictMatch(home, away);
    }
    const diff = away.fifa_rank - home.fifa_rank;
    const p = 1 / (1 + Math.exp(-diff / 8));
    return {
      winner: p >= 0.5 ? home : away,
      confidence: Math.round(Math.abs(p - 0.5) * 200)
    };
  }

  return {
    load, reload, startPolling, stopPolling, onRefresh, clearRefreshListeners,
    getTeams, getMatches, getTeam, getVenue, getSquad, getLastUpdated, predict
  };
})();
