// Generates data/squads.json for all 48 teams.
// Player rows: [name, position, rating, club]
// Positions: GK, CB, LB, RB, CDM, CM, CAM, LW, RW, ST
// Ratings are FC 26 estimates — refine via scripts/scrape_fc26.js when needed.

const fs = require('fs');
const path = require('path');

const T = {
  // ============= GROUP A =============
  CZE: [
    ['Matěj Kovář','GK',79,'PSV Eindhoven'],
    ['Jindřich Staněk','GK',76,'Slavia Prague'],
    ['Ladislav Krejčí','CB',79,'Girona'],
    ['Robin Hranáč','CB',77,'Wolfsburg'],
    ['David Zima','CB',75,'Torino'],
    ['Vladimír Coufal','RB',76,'Hoffenheim'],
    ['David Jurásek','LB',74,'Hoffenheim'],
    ['Tomáš Souček','CDM',81,'West Ham'],
    ['Lukáš Provod','CM',77,'Slavia Prague'],
    ['Michal Sadílek','CM',75,'Slavia Prague'],
    ['Pavel Šulc','CAM',77,'Lyon'],
    ['Adam Hložek','LW',79,'Hoffenheim'],
    ['Mojmír Chytil','RW',74,'Slavia Prague'],
    ['Patrik Schick','ST',82,'Bayer Leverkusen'],
    ['Jan Kuchta','ST',75,'Sparta Prague'],
  ],
  MEX: [
    ['Guillermo Ochoa','GK',78,'AEL Limassol'],
    ['Raúl Rangel','GK',75,'Guadalajara'],
    ['Edson Álvarez','CB',82,'Fenerbahçe'],
    ['Johan Vásquez','CB',79,'Genoa'],
    ['César Montes','CB',77,'Lokomotiv Moscow'],
    ['Jorge Sánchez','RB',75,'PAOK'],
    ['Jesús Gallardo','LB',76,'Toluca'],
    ['Luis Romo','CDM',77,'Guadalajara'],
    ['Érik Lira','CM',75,'Cruz Azul'],
    ['Luis Chávez','CM',77,'Dynamo Moscow'],
    ['Orbelín Pineda','CAM',77,'AEK Athens'],
    ['Hirving Lozano','LW',81,'San Diego FC'],
    ['Alexis Vega','RW',77,'Toluca'],
    ['Santiago Giménez','ST',82,'Milan'],
    ['Raúl Jiménez','ST',79,'Fulham'],
    ['Julián Quiñones','ST',78,'Al-Qadsiah'],
  ],
  RSA: [
    ['Ronwen Williams','GK',79,'Mamelodi Sundowns'],
    ['Sipho Chaine','GK',73,'Orlando Pirates'],
    ['Nkosinathi Sibisi','CB',73,'Orlando Pirates'],
    ['Khuliso Mudau','CB',72,'Mamelodi Sundowns'],
    ['Mbekezeli Mbokazi','CB',71,'Chicago Fire'],
    ['Khulumani Ndamane','RB',71,'Mamelodi Sundowns'],
    ['Aubrey Modiba','LB',74,'Mamelodi Sundowns'],
    ['Teboho Mokoena','CDM',77,'Mamelodi Sundowns'],
    ['Sphephelo Sithole','CM',73,'Tondela'],
    ['Thalente Mbatha','CM',72,'Orlando Pirates'],
    ['Themba Zwane','CAM',77,'Mamelodi Sundowns'],
    ['Relebohile Mofokeng','LW',76,'Orlando Pirates'],
    ['Oswin Appollis','RW',74,'Orlando Pirates'],
    ['Lyle Foster','ST',77,'Burnley'],
    ['Iqraam Rayners','ST',73,'Mamelodi Sundowns'],
  ],
  KOR: [
    ['Kim Seung-gyu','GK',77,'FC Tokyo'],
    ['Jo Hyeon-woo','GK',74,'Ulsan HD'],
    ['Kim Min-jae','CB',86,'Bayern Munich'],
    ['Kim Young-gwon','CB',79,'Ulsan HD'],
    ['Lee Han-beom','CB',75,'Midtjylland'],
    ['Seol Young-woo','RB',75,'Red Star Belgrade'],
    ['Kim Moon-hwan','LB',74,'Daejeon Hana'],
    ['Hwang In-beom','CDM',80,'Feyenoord'],
    ['Paik Seung-ho','CM',77,'Birmingham City'],
    ['Lee Jae-sung','CM',79,'Mainz 05'],
    ['Lee Kang-in','CAM',83,'Paris Saint-Germain'],
    ['Hwang Hee-chan','LW',81,'Wolverhampton'],
    ['Bae Jun-ho','RW',76,'Stoke City'],
    ['Son Heung-min','ST',87,'Los Angeles FC'],
    ['Cho Gue-sung','ST',76,'Midtjylland'],
    ['Oh Hyeon-gyu','ST',74,'Beşiktaş'],
  ],

  // ============= GROUP B =============
  BIH: [
    ['Nikola Vasilj','GK',76,'FC St. Pauli'],
    ['Mladen Jurkas','GK',71,'Borac Banja Luka'],
    ['Sead Kolašinac','CB',78,'Atalanta'],
    ['Nihad Mujakić','CB',74,'Gaziantep'],
    ['Amar Dedić','RB',77,'Benfica'],
    ['Tarik Muharemović','CB',74,'Sassuolo'],
    ['Stjepan Radeljić','LB',71,'Rijeka'],
    ['Benjamin Tahirović','CDM',76,'Brøndby'],
    ['Amir Hadžiahmetović','CM',76,'Hull City'],
    ['Armin Gigović','CM',74,'Young Boys'],
    ['Ivan Šunjić','CAM',75,'Pafos'],
    ['Ermedin Demirović','LW',79,'VfB Stuttgart'],
    ['Samed Baždar','RW',73,'Jagiellonia'],
    ['Edin Džeko','ST',81,'Schalke 04'],
    ['Haris Tabaković','ST',76,'Borussia M\'gladbach'],
  ],
  CAN: [
    ['Dayne St. Clair','GK',79,'Inter Miami'],
    ['Maxime Crépeau','GK',75,'Orlando City'],
    ['Alphonso Davies','LB',85,'Bayern Munich'],
    ['Moïse Bombito','CB',77,'Nice'],
    ['Derek Cornelius','CB',74,'Rangers'],
    ['Alistair Johnston','RB',79,'Celtic'],
    ['Joel Waterman','CB',72,'Chicago Fire'],
    ['Stephen Eustáquio','CDM',79,'Los Angeles FC'],
    ['Ismaël Koné','CM',76,'Sassuolo'],
    ['Mathieu Choinière','CM',74,'Los Angeles FC'],
    ['Liam Millar','CAM',75,'Hull City'],
    ['Tajon Buchanan','LW',79,'Villarreal'],
    ['Jacob Shaffelburg','RW',76,'Los Angeles FC'],
    ['Jonathan David','ST',83,'Juventus'],
    ['Cyle Larin','ST',76,'Southampton'],
    ['Tani Oluwaseyi','ST',75,'Villarreal'],
  ],
  QAT: [
    ['Mahmud Abunada','GK',73,'Al-Rayyan'],
    ['Saad Al-Sheeb','GK',72,'Al-Sadd'],
    ['Pedro Miguel','CB',73,'Al-Sadd'],
    ['Boualem Khoukhi','CB',72,'Al-Arabi'],
    ['Tarek Salman','CB',71,'Al-Sadd'],
    ['Homam Ahmed','RB',71,'Cultural Leonesa'],
    ['Lucas Mendes','LB',72,'Al-Wakrah'],
    ['Karim Boudiaf','CDM',75,'Al-Duhail'],
    ['Abdulaziz Hatem','CM',73,'Al-Rayyan'],
    ['Hassan Al-Haydos','CM',74,'Al-Sadd'],
    ['Akram Afif','CAM',81,'Al-Sadd'],
    ['Edmilson Junior','LW',76,'Al-Duhail'],
    ['Ahmed Alaaeldin','RW',73,'Al-Rayyan'],
    ['Almoez Ali','ST',77,'Al-Duhail'],
    ['Mohammed Muntari','ST',73,'Al-Gharafa'],
  ],
  SUI: [
    ['Yann Sommer','GK',83,'Inter Milan'],
    ['Gregor Kobel','GK',83,'Borussia Dortmund'],
    ['Manuel Akanji','CB',83,'Inter Milan'],
    ['Nico Elvedi','CB',79,'Borussia M\'gladbach'],
    ['Fabian Schär','CB',79,'Newcastle'],
    ['Silvan Widmer','RB',76,'Mainz 05'],
    ['Ricardo Rodriguez','LB',77,'Real Betis'],
    ['Granit Xhaka','CDM',83,'Sunderland'],
    ['Remo Freuler','CM',78,'Bologna'],
    ['Denis Zakaria','CM',79,'Monaco'],
    ['Xherdan Shaqiri','CAM',79,'Chicago Fire'],
    ['Ruben Vargas','LW',77,'Sevilla'],
    ['Dan Ndoye','RW',79,'Nottingham Forest'],
    ['Breel Embolo','ST',80,'Rennes'],
    ['Zeki Amdouni','ST',76,'Benfica'],
  ],

  // ============= GROUP C =============
  BRA: [
    ['Alisson','GK',89,'Liverpool'],
    ['Ederson','GK',86,'Manchester City'],
    ['Marquinhos','CB',86,'Paris Saint-Germain'],
    ['Gabriel Magalhães','CB',85,'Arsenal'],
    ['Éder Militão','CB',83,'Real Madrid'],
    ['Danilo','RB',80,'Flamengo'],
    ['Vanderson','RB',77,'Monaco'],
    ['Wendell','LB',77,'Porto'],
    ['Casemiro','CDM',83,'Manchester United'],
    ['Bruno Guimarães','CDM',85,'Newcastle'],
    ['Lucas Paquetá','CM',82,'West Ham'],
    ['Vinícius Júnior','LW',90,'Real Madrid'],
    ['Raphinha','RW',86,'Barcelona'],
    ['Rodrygo','RW',85,'Real Madrid'],
    ['Endrick','ST',82,'Real Madrid'],
    ['Estêvão','RW',83,'Chelsea'],
    ['Richarlison','ST',81,'Tottenham'],
  ],
  HAI: [
    ['Johnny Placide','GK',71,'Le Havre'],
    ['Jhonny Casimir','GK',68,'Cavalry FC'],
    ['Ricardo Adé','CB',74,'Toulouse'],
    ['Andrew Jean-Baptiste','CB',71,'CSKA Sofia'],
    ['Carlens Arcus','RB',72,'Auxerre'],
    ['Garven Metusala','LB',71,'Independiente Petrolero'],
    ['Christopher Attys','CB',69,'Salernitana'],
    ['Danley Jean Jacques','CDM',73,'Persikabo'],
    ['Leverton Pierre','CM',71,'Olympic FC'],
    ['Steeven Saba','CM',70,'Ümraniyespor'],
    ['Derrick Etienne','CAM',75,'Columbus Crew'],
    ['Frantzdy Pierrot','ST',74,'AEL Limassol'],
    ['Don Deedson Louicius','LW',71,'Olympic FC'],
    ['Duckens Nazon','ST',72,'Anorthosis'],
    ['Steven Sanon','RW',70,'Persikabo'],
  ],
  MAR: [
    ['Yassine Bounou','GK',84,'Al-Hilal'],
    ['Munir Mohamedi','GK',76,'Al-Wehda'],
    ['Achraf Hakimi','RB',87,'Paris Saint-Germain'],
    ['Romain Saïss','CB',79,'Al-Shabab'],
    ['Nayef Aguerd','CB',81,'Real Sociedad'],
    ['Noussair Mazraoui','RB',81,'Manchester United'],
    ['Adam Masina','LB',76,'Torino'],
    ['Sofyan Amrabat','CDM',81,'Fenerbahçe'],
    ['Azzedine Ounahi','CM',80,'Girona'],
    ['Bilal El Khannouss','CAM',80,'VfB Stuttgart'],
    ['Ismael Saibari','CAM',81,'PSV Eindhoven'],
    ['Hakim Ziyech','RW',81,'Al-Duhail'],
    ['Sofiane Boufal','LW',78,'Al-Rayyan'],
    ['Brahim Díaz','CAM',83,'Real Madrid'],
    ['Youssef En-Nesyri','ST',81,'Fenerbahçe'],
    ['Soufiane Rahimi','ST',78,'Al Ain'],
  ],
  SCO: [
    ['Angus Gunn','GK',77,'Nottingham Forest'],
    ['Craig Gordon','GK',75,'Hearts'],
    ['Kieran Tierney','LB',80,'Celtic'],
    ['Andy Robertson','LB',83,'Liverpool'],
    ['Scott McKenna','CB',76,'Las Palmas'],
    ['Grant Hanley','CB',76,'Birmingham City'],
    ['Aaron Hickey','RB',77,'Brentford'],
    ['Scott McTominay','CM',83,'Napoli'],
    ['Billy Gilmour','CDM',79,'Brighton'],
    ['John McGinn','CM',81,'Aston Villa'],
    ['Ryan Christie','CAM',77,'Bournemouth'],
    ['Ben Doak','RW',76,'Bournemouth'],
    ['Scott McKenna','LW',74,'Las Palmas'],
    ['Che Adams','ST',78,'Torino'],
    ['Lyndon Dykes','ST',75,'Birmingham City'],
  ],

  // ============= GROUP D =============
  AUS: [
    ['Mathew Ryan','GK',78,'Lens'],
    ['Joe Gauci','GK',74,'Aston Villa'],
    ['Harry Souttar','CB',77,'Sheffield United'],
    ['Kye Rowles','CB',76,'Hearts'],
    ['Cameron Burgess','CB',74,'Ipswich Town'],
    ['Nathaniel Atkinson','RB',74,'Hearts'],
    ['Aziz Behich','LB',75,'Melbourne City'],
    ['Aiden O\'Neill','CDM',76,'Standard Liège'],
    ['Jackson Irvine','CM',77,'FC St. Pauli'],
    ['Connor Metcalfe','CM',75,'FC St. Pauli'],
    ['Riley McGree','CAM',76,'Middlesbrough'],
    ['Awer Mabil','LW',75,'Grasshoppers'],
    ['Martin Boyle','RW',76,'Al-Faisaly'],
    ['Mitchell Duke','ST',74,'Machida Zelvia'],
    ['Kusini Yengi','ST',73,'Portsmouth'],
  ],
  PAR: [
    ['Roberto Fernández','GK',76,'Cerro Porteño'],
    ['Carlos Coronel','GK',73,'NY Red Bulls'],
    ['Junior Alonso','CB',78,'Krasnodar'],
    ['Omar Alderete','CB',77,'Getafe'],
    ['Gustavo Velázquez','CB',74,'Newell\'s Old Boys'],
    ['Robert Rojas','RB',75,'River Plate'],
    ['Juan Cáceres','LB',73,'Boca Juniors'],
    ['Andrés Cubas','CDM',77,'Vancouver Whitecaps'],
    ['Mathías Villasanti','CM',76,'Grêmio'],
    ['Damián Bobadilla','CM',74,'São Paulo'],
    ['Miguel Almirón','CAM',79,'Atlanta United'],
    ['Julio Enciso','RW',78,'Ipswich Town'],
    ['Diego Gómez','LW',77,'Brighton'],
    ['Antonio Sanabria','ST',77,'Torino'],
    ['Adam Bareiro','ST',75,'River Plate'],
  ],
  TUR: [
    ['Altay Bayındır','GK',77,'Manchester United'],
    ['Uğurcan Çakır','GK',79,'Galatasaray'],
    ['Merih Demiral','CB',81,'Al-Ahli'],
    ['Çağlar Söyüncü','CB',77,'Fenerbahçe'],
    ['Samet Akaydin','CB',75,'Pendikspor'],
    ['Zeki Çelik','RB',77,'Roma'],
    ['Ferdi Kadıoğlu','LB',82,'Brighton'],
    ['Hakan Çalhanoğlu','CDM',86,'Inter Milan'],
    ['Salih Özcan','CM',78,'Borussia Dortmund'],
    ['Orkun Kökçü','CM',79,'Benfica'],
    ['Arda Güler','CAM',83,'Real Madrid'],
    ['Kenan Yıldız','LW',83,'Juventus'],
    ['Yunus Akgün','RW',77,'Galatasaray'],
    ['Kerem Aktürkoğlu','LW',80,'Benfica'],
    ['Baris Alper Yilmaz','RW',77,'Galatasaray'],
    ['Cenk Tosun','ST',76,'Beşiktaş'],
  ],
  USA: [
    ['Matt Turner','GK',78,'New England'],
    ['Patrick Schulte','GK',76,'Columbus Crew'],
    ['Chris Richards','CB',79,'Crystal Palace'],
    ['Tim Ream','CB',76,'Charlotte FC'],
    ['Cameron Carter-Vickers','CB',79,'Celtic'],
    ['Sergiño Dest','RB',79,'PSV Eindhoven'],
    ['Antonee Robinson','LB',82,'Fulham'],
    ['Tyler Adams','CDM',80,'Bournemouth'],
    ['Weston McKennie','CM',81,'Juventus'],
    ['Yunus Musah','CM',79,'Atalanta'],
    ['Gio Reyna','CAM',79,'Borussia M\'gladbach'],
    ['Christian Pulisic','LW',85,'Milan'],
    ['Tim Weah','RW',79,'Marseille'],
    ['Folarin Balogun','ST',79,'Monaco'],
    ['Ricardo Pepi','ST',78,'PSV Eindhoven'],
    ['Haji Wright','ST',76,'Coventry'],
  ],

  // ============= GROUP E =============
  CUW: [
    ['Eloy Room','GK',74,'Columbus Crew'],
    ['Kenji Gorré','GK',69,'Cracovia'],
    ['Cuco Martina','CB',71,'NEC Nijmegen'],
    ['Juriën Gaari','CB',70,'Suwon FC'],
    ['Roshon van Eijma','CB',69,'Heracles'],
    ['Shurandy Sambo','RB',73,'PSV Eindhoven'],
    ['Armando Obispo','LB',72,'PSV Eindhoven'],
    ['Leandro Bacuna','CM',73,'Birmingham City'],
    ['Juninho Bacuna','CM',73,'Coventry'],
    ['Jürgen Locadia','CAM',73,'OFI Crete'],
    ['Roly Bonevacia','CAM',71,'Western Sydney'],
    ['Tahith Chong','LW',75,'Sheffield United'],
    ['Anthony van den Hurk','RW',69,'IFK Mariehamn'],
    ['Brandley Kuwas','RW',72,'Hapoel Beer Sheva'],
    ['Gervane Kastaneer','ST',71,'Levski Sofia'],
  ],
  ECU: [
    ['Hernán Galíndez','GK',75,'Huracán'],
    ['Alexander Domínguez','GK',74,'LDU Quito'],
    ['Piero Hincapié','CB',82,'Arsenal'],
    ['Willian Pacho','CB',83,'Paris Saint-Germain'],
    ['Félix Torres','CB',76,'Corinthians'],
    ['Ángelo Preciado','RB',77,'Genk'],
    ['Pervis Estupiñán','LB',81,'Milan'],
    ['Moisés Caicedo','CDM',86,'Chelsea'],
    ['Alan Franco','CM',76,'Atlético Mineiro'],
    ['Kendry Páez','CAM',81,'Strasbourg'],
    ['Jeremy Sarmiento','CAM',76,'Burnley'],
    ['Gonzalo Plata','RW',78,'Flamengo'],
    ['Kevin Rodríguez','ST',76,'Union Saint-Gilloise'],
    ['Enner Valencia','ST',79,'Internacional'],
    ['Leonardo Campana','ST',76,'Inter Miami'],
  ],
  GER: [
    ['Marc-André ter Stegen','GK',88,'Barcelona'],
    ['Oliver Baumann','GK',79,'Hoffenheim'],
    ['Antonio Rüdiger','CB',86,'Real Madrid'],
    ['Jonathan Tah','CB',84,'Bayern Munich'],
    ['Nico Schlotterbeck','CB',82,'Borussia Dortmund'],
    ['Joshua Kimmich','RB',86,'Bayern Munich'],
    ['David Raum','LB',79,'RB Leipzig'],
    ['Aleksandar Pavlović','CDM',81,'Bayern Munich'],
    ['Pascal Gross','CM',80,'Borussia Dortmund'],
    ['Florian Wirtz','CAM',88,'Liverpool'],
    ['Jamal Musiala','CAM',88,'Bayern Munich'],
    ['Leroy Sané','LW',83,'Galatasaray'],
    ['Karim Adeyemi','RW',81,'Borussia Dortmund'],
    ['Kai Havertz','ST',83,'Arsenal'],
    ['Niclas Füllkrug','ST',79,'West Ham'],
    ['Deniz Undav','ST',80,'VfB Stuttgart'],
  ],
  CIV: [
    ['Yahia Fofana','GK',76,'Angers'],
    ['Mohamed Koné','GK',73,'Mamelodi Sundowns'],
    ['Willy Boly','CB',77,'Al-Shabab'],
    ['Odilon Kossounou','CB',79,'Atalanta'],
    ['Eric Bailly','CB',75,'AC Ajaccio'],
    ['Wilfried Singo','RB',81,'Monaco'],
    ['Ghislain Konan','LB',74,'Stade de Reims'],
    ['Franck Kessié','CDM',81,'Al-Ahli'],
    ['Seko Fofana','CM',79,'Rennes'],
    ['Ibrahim Sangaré','CDM',81,'Nottingham Forest'],
    ['Simon Adingra','LW',80,'Sunderland'],
    ['Nicolas Pépé','RW',78,'Villarreal'],
    ['Karim Konaté','ST',76,'Red Bull Salzburg'],
    ['Sébastien Haller','ST',79,'Utrecht'],
    ['Jonathan Bamba','LW',77,'Celta Vigo'],
  ],

  // ============= GROUP F =============
  JPN: [
    ['Zion Suzuki','GK',81,'Parma'],
    ['Daniel Schmidt','GK',76,'Sint-Truiden'],
    ['Takehiro Tomiyasu','CB',81,'Arsenal'],
    ['Ko Itakura','CB',81,'Ajax'],
    ['Shogo Taniguchi','CB',77,'Sint-Truiden'],
    ['Hiroki Sakai','RB',76,'Auckland City'],
    ['Yukinari Sugawara','RB',79,'Southampton'],
    ['Hiroki Ito','LB',79,'Bayern Munich'],
    ['Wataru Endo','CDM',81,'Liverpool'],
    ['Hidemasa Morita','CM',79,'Sporting CP'],
    ['Takefusa Kubo','RW',83,'Real Sociedad'],
    ['Ritsu Doan','CAM',81,'Eintracht Frankfurt'],
    ['Kaoru Mitoma','LW',83,'Brighton'],
    ['Daichi Kamada','CAM',81,'Crystal Palace'],
    ['Takumi Minamino','LW',79,'Monaco'],
    ['Ayase Ueda','ST',79,'Feyenoord'],
  ],
  NED: [
    ['Bart Verbruggen','GK',82,'Brighton'],
    ['Mark Flekken','GK',79,'Brentford'],
    ['Virgil van Dijk','CB',88,'Liverpool'],
    ['Matthijs de Ligt','CB',83,'Manchester United'],
    ['Lutsharel Geertruida','CB',79,'RB Leipzig'],
    ['Denzel Dumfries','RB',82,'Inter Milan'],
    ['Nathan Aké','LB',81,'Manchester City'],
    ['Frenkie de Jong','CDM',85,'Barcelona'],
    ['Tijjani Reijnders','CM',84,'Manchester City'],
    ['Joey Veerman','CM',79,'PSV Eindhoven'],
    ['Xavi Simons','CAM',83,'Leipzig'],
    ['Cody Gakpo','LW',83,'Liverpool'],
    ['Jeremie Frimpong','RW',82,'Liverpool'],
    ['Memphis Depay','ST',80,'Corinthians'],
    ['Wout Weghorst','ST',77,'Ajax'],
    ['Brian Brobbey','ST',78,'RB Leipzig'],
  ],
  SWE: [
    ['Robin Olsen','GK',77,'Aston Villa'],
    ['Viktor Johansson','GK',76,'Stoke City'],
    ['Victor Lindelöf','CB',79,'Aston Villa'],
    ['Gabriel Gudmundsson','LB',78,'Leeds United'],
    ['Isak Hien','CB',80,'Atalanta'],
    ['Emil Krafth','RB',76,'Newcastle'],
    ['Anton Salétros','CM',75,'AIK'],
    ['Mattias Svanberg','CM',78,'Wolfsburg'],
    ['Jens Cajuste','CDM',77,'Ipswich Town'],
    ['Anthony Elanga','LW',81,'Newcastle'],
    ['Dejan Kulusevski','CAM',83,'Tottenham'],
    ['Alexander Isak','ST',86,'Liverpool'],
    ['Viktor Gyökeres','ST',86,'Arsenal'],
    ['Jesper Karlsson','RW',78,'Bologna'],
    ['Lucas Bergvall','CM',79,'Tottenham'],
  ],
  TUN: [
    ['Aymen Dahmen','GK',75,'Sfaxien'],
    ['Bechir Ben Saïd','GK',73,'US Monastir'],
    ['Yan Valery','CB',75,'Angers'],
    ['Montassar Talbi','CB',76,'Lorient'],
    ['Dylan Bronn','CB',76,'Salernitana'],
    ['Mohamed Dräger','RB',74,'Luzern'],
    ['Ali Abdi','LB',74,'Caen'],
    ['Aïssa Laidouni','CDM',77,'Union Berlin'],
    ['Ellyes Skhiri','CM',79,'Eintracht Frankfurt'],
    ['Hannibal Mejbri','CAM',76,'Burnley'],
    ['Mohamed Ben Romdhane','CM',74,'Ferencváros'],
    ['Anis Ben Slimane','LW',75,'Sheffield United'],
    ['Naïm Sliti','RW',75,'Al-Ettifaq'],
    ['Wahbi Khazri','CAM',76,'Montpellier'],
    ['Issam Jebali','ST',74,'Odense'],
  ],

  // ============= GROUP G =============
  BEL: [
    ['Thibaut Courtois','GK',89,'Real Madrid'],
    ['Koen Casteels','GK',81,'Al-Qadsiah'],
    ['Wout Faes','CB',79,'Leicester City'],
    ['Jan Vertonghen','CB',77,'Anderlecht'],
    ['Zeno Debast','CB',79,'Sporting CP'],
    ['Timothy Castagne','RB',79,'Fulham'],
    ['Maxim De Cuyper','LB',77,'Brighton'],
    ['Amadou Onana','CDM',82,'Aston Villa'],
    ['Youri Tielemans','CM',83,'Aston Villa'],
    ['Kevin De Bruyne','CAM',88,'Napoli'],
    ['Charles De Ketelaere','CAM',81,'Atalanta'],
    ['Jérémy Doku','LW',82,'Manchester City'],
    ['Leandro Trossard','LW',81,'Arsenal'],
    ['Dodi Lukebakio','RW',79,'Sevilla'],
    ['Romelu Lukaku','ST',82,'Napoli'],
    ['Loïs Openda','ST',82,'Juventus'],
  ],
  EGY: [
    ['Mohamed El-Shenawy','GK',77,'Al Ahly'],
    ['Mohamed Sobhi','GK',74,'Pyramids'],
    ['Mohamed Hany','RB',74,'Al Ahly'],
    ['Mohamed Abdelmonem','CB',76,'Al Ahly'],
    ['Omar Kamal','CB',74,'Zamalek'],
    ['Mohamed Hamdy','LB',73,'Pyramids'],
    ['Ahmed Hegazi','CB',75,'Ittihad'],
    ['Mohamed Elneny','CDM',76,'Al-Jazira'],
    ['Mostafa Mohamed','ST',77,'Nantes'],
    ['Trezeguet','LW',77,'Trabzonspor'],
    ['Mahmoud Hassan','CM',76,'Trabzonspor'],
    ['Omar Marmoush','ST',83,'Manchester City'],
    ['Mohamed Salah','RW',89,'Liverpool'],
    ['Emam Ashour','CAM',78,'Al Ahly'],
    ['Ibrahim Adel','LW',76,'Pyramids'],
  ],
  IRN: [
    ['Alireza Beiranvand','GK',77,'Persepolis'],
    ['Hossein Hosseini','GK',74,'Esteghlal'],
    ['Sardar Azmoun','ST',81,'Shabab Al-Ahli'],
    ['Mehdi Taremi','ST',83,'Olympiacos'],
    ['Ehsan Hajsafi','LB',76,'AEK Athens'],
    ['Milad Mohammadi','LB',74,'Atromitos'],
    ['Saleh Hardani','RB',73,'Esteghlal'],
    ['Morteza Pouraliganji','CB',75,'Persepolis'],
    ['Majid Hosseini','CB',74,'Kayserispor'],
    ['Saeid Ezatolahi','CDM',76,'Esteghlal'],
    ['Ahmad Nourollahi','CM',76,'Shabab Al-Ahli'],
    ['Alireza Jahanbakhsh','RW',77,'Heerenveen'],
    ['Mehdi Ghayedi','LW',76,'Ittihad Kalba'],
    ['Saman Ghoddos','CAM',76,'Brentford'],
    ['Mohammad Mohebi','LW',74,'Rostov'],
  ],
  NZL: [
    ['Max Crocombe','GK',73,'Burton Albion'],
    ['Oliver Sail','GK',71,'Wellington Phoenix'],
    ['Michael Boxall','CB',74,'Minnesota United'],
    ['Tyler Bindon','CB',74,'Nottingham Forest'],
    ['Liberato Cacace','LB',76,'Wellington Phoenix'],
    ['Finn Surman','CB',71,'Portland Timbers'],
    ['Joe Bell','CDM',75,'Viking'],
    ['Marko Stamenić','CM',74,'Olympiacos'],
    ['Matt Garbett','CM',73,'Sheffield Wednesday'],
    ['Sarpreet Singh','CAM',73,'Hannover 96'],
    ['Callum McCowatt','LW',72,'Helsingborg'],
    ['Chris Wood','ST',80,'Nottingham Forest'],
    ['Kosta Barbarouses','RW',73,'Wellington Phoenix'],
    ['Ben Old','LW',72,'St. Mirren'],
    ['Eli Just','ST',71,'Norrby IF'],
  ],

  // ============= GROUP H =============
  CPV: [
    ['Vozinha','GK',74,'Pacos de Ferreira'],
    ['Márcio Rosa','GK',71,'Olhanense'],
    ['Stopira','CB',73,'Apollon Smyrnis'],
    ['Steven Fortes','CB',73,'Estoril'],
    ['Roberto Lopes','CB',74,'Shamrock Rovers'],
    ['Diney','RB',72,'Estoril'],
    ['Sidny Cabral','LB',72,'Mafra'],
    ['Kenny Rocha','CDM',74,'Servette'],
    ['Jamiro Monteiro','CM',76,'San Diego FC'],
    ['Laros Duarte','CAM',74,'Sint-Truiden'],
    ['Bryan Teixeira','CM',72,'Reims'],
    ['Garry Rodrigues','LW',74,'Adana Demirspor'],
    ['Bebé','RW',73,'Sumqayit'],
    ['Ryan Mendes','ST',75,'Al-Najma'],
    ['Willy Semedo','ST',73,'Karmiotissa'],
  ],
  KSA: [
    ['Mohammed Al-Owais','GK',77,'Al-Hilal'],
    ['Nawaf Al-Aqidi','GK',75,'Al-Najma'],
    ['Hassan Tambakti','CB',77,'Al-Hilal'],
    ['Abdulelah Al-Amri','CB',75,'Al-Nassr'],
    ['Ali Al-Bulayhi','CB',76,'Al-Hilal'],
    ['Saud Abdulhamid','RB',76,'Roma'],
    ['Yasir Al-Shahrani','LB',76,'Al-Hilal'],
    ['Mohamed Kanno','CDM',76,'Al-Hilal'],
    ['Salman Al-Faraj','CM',76,'Al-Hilal'],
    ['Ayman Yahya','CM',74,'Al-Nassr'],
    ['Salem Al-Dawsari','LW',81,'Al-Hilal'],
    ['Saleh Al-Shehri','ST',76,'Al-Hilal'],
    ['Firas Al-Buraikan','ST',77,'Al-Ahli'],
    ['Abdullah Al-Hamdan','ST',75,'Al-Shabab'],
    ['Musab Al-Juwayr','CAM',75,'Al-Hilal'],
  ],
  ESP: [
    ['Unai Simón','GK',85,'Athletic Bilbao'],
    ['David Raya','GK',85,'Arsenal'],
    ['Aymeric Laporte','CB',83,'Athletic Bilbao'],
    ['Robin Le Normand','CB',82,'Atlético Madrid'],
    ['Pau Cubarsí','CB',83,'Barcelona'],
    ['Daniel Carvajal','RB',85,'Real Madrid'],
    ['Marc Cucurella','LB',81,'Chelsea'],
    ['Rodri','CDM',91,'Manchester City'],
    ['Pedri','CM',88,'Barcelona'],
    ['Mikel Merino','CM',82,'Arsenal'],
    ['Fabián Ruiz','CM',83,'Paris Saint-Germain'],
    ['Lamine Yamal','RW',90,'Barcelona'],
    ['Nico Williams','LW',86,'Barcelona'],
    ['Dani Olmo','CAM',84,'Barcelona'],
    ['Álvaro Morata','ST',82,'Como'],
    ['Mikel Oyarzabal','ST',83,'Real Sociedad'],
  ],
  URU: [
    ['Sergio Rochet','GK',79,'Internacional'],
    ['Santiago Mele','GK',76,'Junior'],
    ['Ronald Araújo','CB',86,'Barcelona'],
    ['José María Giménez','CB',83,'Atlético Madrid'],
    ['Mathías Olivera','LB',80,'Napoli'],
    ['Nahitan Nández','RB',78,'Al-Qadsiah'],
    ['Joaquín Piquerez','LB',77,'Palmeiras'],
    ['Federico Valverde','CM',88,'Real Madrid'],
    ['Manuel Ugarte','CDM',82,'Manchester United'],
    ['Rodrigo Bentancur','CM',83,'Tottenham'],
    ['Nicolás de la Cruz','CAM',81,'Flamengo'],
    ['Maximiliano Araújo','LW',79,'Sporting CP'],
    ['Brian Rodríguez','RW',77,'América'],
    ['Darwin Núñez','ST',83,'Al-Hilal'],
    ['Facundo Pellistri','RW',78,'Panathinaikos'],
    ['Rodrigo Aguirre','ST',76,'América'],
  ],

  // ============= GROUP I =============
  FRA: [
    ['Mike Maignan','GK',86,'Milan'],
    ['Brice Samba','GK',81,'Rennes'],
    ['William Saliba','CB',86,'Arsenal'],
    ['Dayot Upamecano','CB',83,'Bayern Munich'],
    ['Jules Koundé','RB',84,'Barcelona'],
    ['Theo Hernández','LB',83,'Al-Hilal'],
    ['Ibrahima Konaté','CB',83,'Liverpool'],
    ['Aurélien Tchouaméni','CDM',85,'Real Madrid'],
    ['Adrien Rabiot','CM',83,'Milan'],
    ['Eduardo Camavinga','CM',83,'Real Madrid'],
    ['Warren Zaïre-Emery','CM',81,'Paris Saint-Germain'],
    ['Kylian Mbappé','LW',92,'Real Madrid'],
    ['Ousmane Dembélé','RW',86,'Paris Saint-Germain'],
    ['Marcus Thuram','ST',84,'Inter Milan'],
    ['Bradley Barcola','LW',83,'Paris Saint-Germain'],
    ['Randal Kolo Muani','ST',82,'Tottenham'],
    ['Désiré Doué','CAM',83,'Paris Saint-Germain'],
  ],
  IRQ: [
    ['Jalal Hassan','GK',74,'Al-Quwa Al-Jawiya'],
    ['Ahmed Basil','GK',71,'Al-Karkh'],
    ['Zaid Tahseen','CB',73,'Al-Quwa Al-Jawiya'],
    ['Rebin Sulaka','CB',74,'Al-Khaldiya'],
    ['Merchas Doski','CB',73,'KuPS'],
    ['Hussein Ali','RB',73,'Al-Shorta'],
    ['Frans Putros','LB',73,'Al-Najaf'],
    ['Bashar Resan','CM',74,'Al-Najma'],
    ['Amir Al-Ammari','CM',75,'Halmstads BK'],
    ['Hussein Ali Al-Saedi','CDM',73,'Al-Quwa Al-Jawiya'],
    ['Sherko Kareem','CAM',74,'Al-Najaf'],
    ['Ali Al-Hamadi','ST',77,'Ipswich Town'],
    ['Aymen Hussein','ST',75,'Sepahan'],
    ['Mohanad Ali','ST',76,'Al-Duhail'],
    ['Ibrahim Bayesh','LW',74,'Al-Karkh'],
  ],
  NOR: [
    ['Ørjan Nyland','GK',77,'Sevilla'],
    ['Egil Selvik','GK',74,'Brann'],
    ['Kristoffer Ajer','CB',79,'Brentford'],
    ['Leo Østigård','CB',77,'Stade Rennais'],
    ['Stefan Strandberg','CB',74,'Salernitana'],
    ['Julian Ryerson','RB',79,'Borussia Dortmund'],
    ['David Møller Wolfe','LB',74,'AZ Alkmaar'],
    ['Morten Thorsby','CDM',77,'Genoa'],
    ['Sander Berge','CM',79,'Fulham'],
    ['Patrick Berg','CM',76,'Bodø/Glimt'],
    ['Martin Ødegaard','CAM',87,'Arsenal'],
    ['Oscar Bobb','RW',79,'Manchester City'],
    ['Antonio Nusa','LW',79,'RB Leipzig'],
    ['Alexander Sørloth','ST',82,'Atlético Madrid'],
    ['Erling Haaland','ST',92,'Manchester City'],
  ],
  SEN: [
    ['Édouard Mendy','GK',82,'Al-Ahli'],
    ['Seny Dieng','GK',76,'Middlesbrough'],
    ['Kalidou Koulibaly','CB',83,'Al-Hilal'],
    ['Abdou Diallo','CB',79,'Al-Arabi'],
    ['Ismail Jakobs','LB',77,'Galatasaray'],
    ['Krépin Diatta','RB',79,'Monaco'],
    ['Moussa Niakhaté','CB',79,'Lyon'],
    ['Idrissa Gueye','CDM',79,'Everton'],
    ['Pape Matar Sarr','CM',79,'Tottenham'],
    ['Pape Gueye','CM',77,'Villarreal'],
    ['Sadio Mané','LW',83,'Al-Nassr'],
    ['Ismaïla Sarr','RW',81,'Crystal Palace'],
    ['Habib Diarra','CAM',80,'Sunderland'],
    ['Iliman Ndiaye','LW',80,'Everton'],
    ['Nicolas Jackson','ST',81,'Bayern Munich'],
    ['Boulaye Dia','ST',79,'Lazio'],
  ],

  // ============= GROUP J =============
  ALG: [
    ['Raïs M\'Bolhi','GK',76,'CR Belouizdad'],
    ['Anthony Mandrea','GK',73,'Angers'],
    ['Aïssa Mandi','CB',79,'Lille'],
    ['Ramy Bensebaïni','LB',81,'Borussia Dortmund'],
    ['Mohamed Tougaï','CB',75,'Hearts'],
    ['Youcef Atal','RB',77,'Al-Sadd'],
    ['Houssem Aouar','CAM',79,'Al-Ittihad'],
    ['Ismaël Bennacer','CDM',81,'Marseille'],
    ['Nabil Bentaleb','CM',76,'Lille'],
    ['Hicham Boudaoui','CM',77,'Nice'],
    ['Riyad Mahrez','RW',83,'Al-Ahli'],
    ['Saïd Benrahma','LW',79,'Lyon'],
    ['Yassine Benzia','CAM',76,'Qarabağ'],
    ['Islam Slimani','ST',76,'Coritiba'],
    ['Baghdad Bounedjah','ST',77,'Al-Sadd'],
  ],
  ARG: [
    ['Emiliano Martínez','GK',89,'Aston Villa'],
    ['Gerónimo Rulli','GK',81,'Marseille'],
    ['Cristian Romero','CB',85,'Tottenham'],
    ['Nicolás Otamendi','CB',82,'Benfica'],
    ['Lisandro Martínez','CB',84,'Manchester United'],
    ['Nahuel Molina','RB',82,'Atlético Madrid'],
    ['Marcos Acuña','LB',79,'River Plate'],
    ['Rodrigo De Paul','CM',85,'Inter Miami'],
    ['Enzo Fernández','CM',85,'Chelsea'],
    ['Alexis Mac Allister','CM',85,'Liverpool'],
    ['Lionel Messi','RW',92,'Inter Miami'],
    ['Lautaro Martínez','ST',88,'Inter Milan'],
    ['Julián Álvarez','ST',86,'Atlético Madrid'],
    ['Nicolás González','LW',81,'Juventus'],
    ['Ángel Di María','RW',83,'Benfica'],
    ['Giovani Lo Celso','CAM',81,'Real Betis'],
  ],
  AUT: [
    ['Patrick Pentz','GK',78,'Brøndby'],
    ['Heinz Lindner','GK',75,'Union Saint-Gilloise'],
    ['David Alaba','CB',83,'Real Madrid'],
    ['Kevin Danso','CB',80,'Tottenham'],
    ['Maximilian Wöber','CB',77,'Borussia M\'gladbach'],
    ['Stefan Posch','RB',77,'Como'],
    ['Phillipp Mwene','LB',76,'Mainz 05'],
    ['Konrad Laimer','CDM',81,'Bayern Munich'],
    ['Nicolas Seiwald','CM',77,'RB Leipzig'],
    ['Marcel Sabitzer','CM',81,'Borussia Dortmund'],
    ['Christoph Baumgartner','CAM',81,'RB Leipzig'],
    ['Marko Arnautović','ST',79,'Red Star Belgrade'],
    ['Marko Grujić','CM',77,'Porto'],
    ['Michael Gregoritsch','ST',77,'SC Freiburg'],
    ['Romano Schmid','CAM',78,'Werder Bremen'],
    ['Patrick Wimmer','LW',77,'Wolfsburg'],
  ],
  JOR: [
    ['Yazeed Abulaila','GK',75,'Al-Faisaly'],
    ['Abdullah Al-Fakhouri','GK',71,'Al-Faisaly'],
    ['Yazan Al-Arab','CB',74,'Maccabi Petah Tikva'],
    ['Salem Al-Ajalin','CB',73,'Al-Wehdat'],
    ['Bara\' Marei','CB',73,'Al-Faisaly'],
    ['Ehsan Haddad','RB',73,'Al-Wehdat'],
    ['Mohammad Abu Hashish','LB',72,'Al-Ramtha'],
    ['Nour Al-Rawabdeh','CDM',73,'Al-Faisaly'],
    ['Noor Hassan','CM',73,'Al-Faisaly'],
    ['Mahmoud Al-Mardi','CM',73,'Al-Wehdat'],
    ['Musa Al-Taamari','RW',79,'Como'],
    ['Yazan Al-Naimat','LW',74,'Al-Wahda'],
    ['Mahmoud Al-Mawas','CAM',73,'Al-Faisaly'],
    ['Ali Olwan','ST',74,'Anorthosis'],
    ['Hamza Al-Dardour','ST',73,'Maccabi Bnei Reineh'],
  ],

  // ============= GROUP K =============
  COL: [
    ['Camilo Vargas','GK',79,'Atlas'],
    ['David Ospina','GK',78,'Atlético Nacional'],
    ['Davinson Sánchez','CB',81,'Galatasaray'],
    ['Yerry Mina','CB',78,'Cagliari'],
    ['Carlos Cuesta','CB',77,'Galatasaray'],
    ['Daniel Muñoz','RB',81,'Crystal Palace'],
    ['Johan Mojica','LB',78,'Magdeburg'],
    ['Richard Ríos','CDM',81,'Benfica'],
    ['Jefferson Lerma','CM',79,'Crystal Palace'],
    ['James Rodríguez','CAM',82,'Club León'],
    ['Juan Quintero','CAM',78,'Racing Club'],
    ['Luis Díaz','LW',85,'Bayern Munich'],
    ['Jhon Arias','RW',81,'Fluminense'],
    ['Jhon Durán','ST',81,'Fenerbahçe'],
    ['Luis Sinisterra','LW',79,'Cruzeiro'],
    ['Rafael Santos Borré','ST',79,'Internacional'],
  ],
  COD: [
    ['Lionel Mpasi','GK',74,'Rodez'],
    ['Timothy Fayulu','GK',71,'Vejle'],
    ['Chancel Mbemba','CB',81,'Lille'],
    ['Axel Tuanzebe','CB',74,'Burnley'],
    ['Arthur Masuaku','LB',76,'Sunderland'],
    ['Gédéon Kalulu','RB',75,'Lorient'],
    ['Joris Kayembe','LB',74,'Genk'],
    ['Samuel Moutoussamy','CDM',75,'Nantes'],
    ['Charles Pickel','CM',74,'Cremonese'],
    ['Aaron Wan-Bissaka','RB',79,'West Ham'],
    ['Cédric Bakambu','ST',76,'Real Betis'],
    ['Yoane Wissa','LW',81,'Newcastle'],
    ['Silas','RW',77,'Red Star Belgrade'],
    ['Théo Bongonda','LW',75,'Spartak Moscow'],
    ['Meschack Elia','LW',75,'Young Boys'],
  ],
  POR: [
    ['Diogo Costa','GK',85,'Porto'],
    ['Rui Patrício','GK',79,'Al-Ain'],
    ['Rúben Dias','CB',88,'Manchester City'],
    ['Pepe','CB',79,'FC Porto'],
    ['Gonçalo Inácio','CB',82,'Sporting CP'],
    ['João Cancelo','RB',83,'Al-Hilal'],
    ['Nuno Mendes','LB',83,'Paris Saint-Germain'],
    ['Bernardo Silva','CM',86,'Manchester City'],
    ['Bruno Fernandes','CM',86,'Manchester United'],
    ['Rúben Neves','CDM',82,'Al-Hilal'],
    ['Vitinha','CM',85,'Paris Saint-Germain'],
    ['Cristiano Ronaldo','ST',86,'Al-Nassr'],
    ['Rafael Leão','LW',85,'Milan'],
    ['Bernardo Silva','RW',86,'Manchester City'],
    ['João Félix','CAM',81,'Chelsea'],
    ['Gonçalo Ramos','ST',82,'Paris Saint-Germain'],
  ],
  UZB: [
    ['Utkir Yusupov','GK',74,'Pakhtakor'],
    ['Yusuf Nurmatov','GK',71,'Bunyodkor'],
    ['Khojimat Erkinov','CB',75,'Pakhtakor'],
    ['Rustam Ashurmatov','CB',74,'Gangwon FC'],
    ['Bobur Abdikholikov','CB',73,'Pakhtakor'],
    ['Abdukodir Khusanov','CB',82,'Manchester City'],
    ['Sherzod Azamov','RB',73,'Pakhtakor'],
    ['Azizbek Turgunboev','LB',73,'Pakhtakor'],
    ['Otabek Shukurov','CDM',75,'Esteghlal'],
    ['Jaloliddin Masharipov','CAM',77,'Pakhtakor'],
    ['Abbosbek Fayzullaev','LW',79,'CSKA Moscow'],
    ['Ostonjon Urinboev','CM',73,'Pakhtakor'],
    ['Eldor Shomurodov','ST',79,'Roma'],
    ['Igor Sergeev','ST',74,'Pakhtakor'],
    ['Khusayin Norchaev','ST',73,'Lokomotiv Tashkent'],
  ],

  // ============= GROUP L =============
  CRO: [
    ['Dominik Livaković','GK',82,'Girona'],
    ['Ivica Ivušić','GK',76,'Pafos'],
    ['Joško Gvardiol','CB',86,'Manchester City'],
    ['Joško Sutalo','CB',79,'Ajax'],
    ['Borna Sosa','LB',78,'Ajax'],
    ['Josip Stanišić','RB',79,'Bayern Munich'],
    ['Domagoj Vida','CB',76,'AEK Athens'],
    ['Luka Modrić','CM',86,'Milan'],
    ['Mateo Kovačić','CM',83,'Manchester City'],
    ['Marcelo Brozović','CDM',82,'Al-Nassr'],
    ['Lovro Majer','CAM',80,'Wolfsburg'],
    ['Ivan Perišić','LW',80,'Hajduk Split'],
    ['Andrej Kramarić','ST',80,'Hoffenheim'],
    ['Bruno Petković','ST',78,'Dinamo Zagreb'],
    ['Mario Pašalić','CAM',79,'Atalanta'],
    ['Luka Sučić','CM',79,'Real Sociedad'],
  ],
  ENG: [
    ['Jordan Pickford','GK',83,'Everton'],
    ['Dean Henderson','GK',79,'Crystal Palace'],
    ['Marc Guéhi','CB',82,'Liverpool'],
    ['Levi Colwill','CB',81,'Chelsea'],
    ['John Stones','CB',81,'Manchester City'],
    ['Trent Alexander-Arnold','RB',86,'Real Madrid'],
    ['Reece James','RB',82,'Chelsea'],
    ['Luke Shaw','LB',79,'Manchester United'],
    ['Declan Rice','CDM',87,'Arsenal'],
    ['Jude Bellingham','CM',90,'Real Madrid'],
    ['Cole Palmer','CAM',86,'Chelsea'],
    ['Phil Foden','CAM',86,'Manchester City'],
    ['Bukayo Saka','RW',88,'Arsenal'],
    ['Marcus Rashford','LW',82,'Aston Villa'],
    ['Harry Kane','ST',89,'Bayern Munich'],
    ['Ollie Watkins','ST',82,'Aston Villa'],
    ['Anthony Gordon','LW',81,'Newcastle'],
  ],
  GHA: [
    ['Lawrence Ati-Zigi','GK',76,'St. Gallen'],
    ['Richard Ofori','GK',73,'Orlando Pirates'],
    ['Mohammed Salisu','CB',78,'Monaco'],
    ['Alidu Seidu','CB',76,'Rennes'],
    ['Alexander Djiku','CB',77,'Fenerbahçe'],
    ['Tariq Lamptey','RB',77,'Brighton'],
    ['Gideon Mensah','LB',75,'Salernitana'],
    ['Thomas Partey','CDM',82,'Villarreal'],
    ['Mohammed Kudus','CAM',83,'Tottenham'],
    ['Iddrisu Baba','CM',76,'Almería'],
    ['Salis Abdul Samed','CM',76,'Lens'],
    ['Antoine Semenyo','RW',81,'Bournemouth'],
    ['Inaki Williams','ST',81,'Athletic Bilbao'],
    ['Jordan Ayew','LW',78,'Leicester City'],
    ['André Ayew','CAM',77,'Le Havre'],
    ['Kamaldeen Sulemana','LW',78,'Atalanta'],
  ],
  PAN: [
    ['Orlando Mosquera','GK',75,'Universidad Católica'],
    ['Luis Mejía','GK',73,'Plaza Amador'],
    ['Iván Anderson','CB',74,'Plaza Amador'],
    ['Andrés Andrade','CB',75,'Universidad Católica'],
    ['Edgar Bárcenas','LB',74,'Mazatlán'],
    ['Michael Murillo','RB',77,'Marseille'],
    ['Adalberto Carrasquilla','CM',77,'Pumas UNAM'],
    ['Christian Martínez','CDM',75,'Sporting San Miguelito'],
    ['Aníbal Godoy','CM',75,'San Diego FC'],
    ['Cristian Martínez','CAM',74,'Independiente del Valle'],
    ['Aldo Quintero','LW',74,'Houston Dynamo'],
    ['Adalberto Carrasquilla','CAM',77,'Pumas UNAM'],
    ['José Fajardo','ST',76,'Pumas UNAM'],
    ['Cecilio Waterman','ST',75,'Coquimbo Unido'],
    ['Ismael Díaz','ST',76,'León'],
  ],
};

// Validate and emit
const out = {};
let totalPlayers = 0;
const teams = JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','teams.json'),'utf8')).teams;
const validCodes = new Set(teams.map(t=>t.code));

for (const code of Object.keys(T)) {
  if (!validCodes.has(code)) { console.warn(`! Unknown team code: ${code}`); continue; }
  const players = T[code].map(([name,pos,rating,club]) => ({name,pos,rating,club}));
  if (players.length < 11) console.warn(`! ${code} has only ${players.length} players (<11)`);
  out[code] = players;
  totalPlayers += players.length;
}

const missing = teams.map(t=>t.code).filter(c=>!out[c]);
if (missing.length) console.warn('! Missing squads for:', missing.join(', '));

fs.writeFileSync(
  path.join(__dirname,'..','data','squads.json'),
  JSON.stringify(out, null, 2) + '\n'
);
console.log(`Wrote ${Object.keys(out).length} squads, ${totalPlayers} players → data/squads.json`);
